### ISSUE TITLE
构建faas时报错

### ISSUE THREAD

**Issue by lijinghui0531** [quanxiang-cloud/quanxiang#49]
现象：在我使用faas创建一个demo示例之后点击了构建，输入版本号v1 前端弹出报错提示
然后再次输入相同的版本号就没有弹出报错提示了，但是在查看构建进度的页面中一直显示 未开始
也就是说每次更换新的版本号第一次进行构建时都会页面都会有错误返回 相同版本号重复构建时不报错但也不执行
错误提示：
![image](https://user-images.githubusercontent.com/24885422/185028621-f917e449-eb2b-4d6e-9a37-8de9886b5c5e.png)

数据库内容：
![image](https://user-images.githubusercontent.com/24885422/185028765-d38f6ebc-bc26-431f-9773-95da2f88d347.png)
表中的namespace值是空的会不会与这个有关
我在调用api/v1/faas/docker时已经将docker信息都写进去了
并且服务器能够登录我配置的harbor仓库
环境：openfunction 0.6.0

**Comment by wentevill** [comment]
namespace是必须的，这是docker仓库的,类似 dockerhub.com/xxx/demo:v1alpha1

**Comment by wentevill** [comment]
构建一直处于未开始，需要查看implant这个服务是否正常工作。implant负责监控构建过程状态，并记录

**Comment by lijinghui0531** [comment]
> 
namespace我尝试用api写进去，但是数据库里是空，我在库里手录namespace也没效果 这个值是不是在redis存了一份？然后应该怎么解决呢

implant 这个服务没有找到相关的pod，他是openfunction的组件还是lowcode的组件 是因为我安装时装的不对吗还是因为镜像版本使用的不对

**Comment by lijinghui0531** [comment]
![image](https://user-images.githubusercontent.com/24885422/185046338-ed30e8cd-2e31-4e93-886c-3185378bb507.png)

**Comment by wentevill** [comment]
[implant](https://github.com/quanxiang-cloud/implant)，使用部署工具没有成功，可以尝试使用
```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: implant
  labels:
    app: implant
spec:
  replicas: 3
  selector:
    matchLabels:
      app: implant
  template:
    metadata:
      labels:
        app: implant
      annotations:
        dapr.io/app-id: implant-dapr
        dapr.io/enabled: 'true'
    spec:
      containers:
        - name: implant
          image: 'qxcr.io/lowcode/implant:v1.1.2'
          command:
            - /ko-app/main.go
            - '-fn-namespace'
            - builder
            - '-svc-namespace'
            - serving
            - '-pubsub'
            - faas-redis-pubsub
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: implantsa
      serviceAccount: implantsa
      securityContext: {}
      schedulerName: default-scheduler
```

**Comment by wentevill** [comment]
> > 
> 
> namespace我尝试用api写进去，但是数据库里是空，我在库里手录namespace也没效果 这个值是不是在redis存了一份？然后应该怎么解决呢

这里没有使用任何的缓存，只需要namespace和docker的namespace保持一致即可。

**Comment by lijinghui0531** [comment]
按照您给的yaml 使用的命令为： apply -f xxx -n lowcode 报错如下： 
![1660719246772_351A6E06-11D1-422d-B011-A293C364E2FD](https://user-images.githubusercontent.com/24885422/185054193-d06eae62-a601-4bd0-86ae-05acfe877740.png)

**Comment by lijinghui0531** [comment]
![1660719246772_351A6E06-11D1-422d-B011-A293C364E2FD](https://user-images.githubusercontent.com/24885422/185054627-bc08d8d1-8b9f-4997-943d-1e734c7dd826.png)

**Comment by lijinghui0531** [comment]
按照您给的yaml 使用的命令为： apply -f xxx -n lowcode 报错如下：
![image](https://user-images.githubusercontent.com/24885422/185054833-34e7b09b-05d1-4f31-9437-612763e9c990.png)

**Comment by wentevill** [comment]
https://github.com/quanxiang-cloud/implant/blob/main/sample/role.yaml
https://github.com/quanxiang-cloud/implant/blob/main/sample/role_binding.yaml
缺少权限，需注意
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: implantBinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: implant
subjects:
  - kind: ServiceAccount
    name: implantsa #deployment使用的serviceAccount
    namespace: lowcode
```
